### PR TITLE
feature: Action to measure test coverage for Flutter projects

### PR DESCRIPTION
**Pull request by Numoy**

### CODE REVIEW

**Review by nasirky — CHANGES_REQUESTED** [review]
@Numoy Why don't we use the same coverage check we used in Gitlab?

**Comment by Numoy** [comment]
The previous coverage check was just a batch script that did not allow (at least not easily) making configuration changes, like which files to exclude or setting the coverage from env file,...

**Comment by Numoy** [comment]
@nasirky Should I change it to the batch script implementation again? Or is it fine to use the new Javascript action?

**Review by nasirky — APPROVED** [review]
LGTM

**Pull request merged**
